// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package graphql

import "fmt"

const _TokenType_name = "EOFUnicodeBOMWhitespaceLineTerminatorCommaSourceCharacterCommentExclamationDollarOpenParenClosedParenSpreadColonEqualsAtOpenBracketClosedBracketOpenBraceClosedBraceVerticalBarNameIntegerFloatStringInvalid"

var _TokenType_index = [...]uint8{0, 3, 13, 23, 37, 42, 57, 64, 75, 81, 90, 101, 107, 112, 118, 120, 131, 144, 153, 164, 175, 179, 186, 191, 197, 204}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return fmt.Sprintf("TokenType(%d)", i)
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
